### ISSUE TITLE
How to integrate nvidia-docker/nvidia-smi information?

### ISSUE THREAD

**Issue by fwarmuth** [levonet/ansible-docker-telegraf#3]
Hey,
i have trouble getting the nvidia-docker to work, i cant figure out how to pass my GPUs to the docker using the `docker_container` ansible instruction.

Any hints?

**Comment by fwarmuth** [comment]
Well it works...
changes:
1. Change the used `telegraf` docker image to `telegraf:latest` by setting `docker_telegraf_image: telegraf:latest` is `defaults/main.yml` or override it outside.
2. Use the latest `docker_container` ansible collection: `ansible-galaxy collection install community.docker`
- make sure to use it by explicitly using it in the task:
`tasks/main.yml`
```
...
- name: Run docker telegraf container
  docker_container:
...
```
to
```
...
- name: Run docker telegraf container
  community.docker.docker_container:
  ...
```
3. Add `device_requests`
```
...
- name: Run docker telegraf container
  community.docker.docker_container:
  ...
    device_requests:
      - # Add nVidia GPUs to this container
        driver: nvidia
        device_ids: 
          - '0'
        capabilities:
          - ['gpu','nvidia']
```
Done
